name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/onregelmatige-werkwoorden-leren-dev 
            
            git pull origin dev 
            
            npm install
            
            npm run build
            
            pm2 restart next-app